export type Color = 'background'
  | 'primary-light'
  | 'primary-medium'
  | 'typography-main'
  | 'border-primary'
  | 'typography-secondary'
  | 'primary'
  | 'primary-dark'
  | 'green-main'
  | 'green-light'
  | 'green-dark'
  | 'black-main'
  | 'grey-main'
  | 'red-main';
